### ISSUE TITLE
1. Portal de Autenticación

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#1]
Creación de portal de Autenticación.

Historias de Usuario:

- [x] 1.1 Diseño Portal Autenticación.
- [x] 1.2 Verificación Información
- [x] 1.3 Log Out

**Comment by rzambrano112** [comment]
Avances Portal Autenticación #1
https://github.com/polieduco/practicaaplicada20172/blob/Hassan/Cliente/RecordarContrasena.html


![image](https://user-images.githubusercontent.com/20976993/31300771-30455d06-aabb-11e7-8114-269995d97725.png)

![image](https://user-images.githubusercontent.com/20976993/31300786-490814a0-aabb-11e7-987f-dd92023247e4.png)

![image](https://user-images.githubusercontent.com/20976993/31300794-54adb120-aabb-11e7-97f0-1c94b508ef95.png)

**Comment by EdnaEspejo** [comment]
1.1 Diseño Portal Autenticación  #2 
1.2 Verificación Información  #6
1.3 Log Out  #159

**Comment by EdnaEspejo** [comment]
Se completaron las historias correspondientes a la épica en mención
