### ISSUE TITLE
2. Modulo I: Portal de Eventos

### ISSUE THREAD

**Issue by mauromara** [polieduco/practicaaplicada20172#10]
Desarrollo de la sección de visualización de eventos.

Historias de usuario:

- [ ] 2.1 Visualización de eventos.
- [ ] 2.2 Acciones sobre los eventos.
- [ ] 2.3 Historial de los Eventos con Créditos.
- [x] 2.4 Notificaciones, Recordatorios de los Eventos.
- [ ] 2.5 Toma de asistencias
- [ ] 2.6 Comentarios Sobre los Eventos

**Comment by EdnaEspejo** [comment]
2.1 Visualización de eventos.   #11 
2.2 Acciones sobre los eventos.   #156 
2.3 Historial de los Eventos con Créditos.    #160 
2.4 Notificaciones, Recordatorios de los Eventos.  #158 
2.5 Toma de asistencias   #113

**Comment by EdnaEspejo** [comment]
2.6 Comentarios Sobre los Eventos   #13

**Comment by rzambrano112** [comment]
Se da cierre a la epica dando cumplimiento al issue crear evento #96
