### ISSUE TITLE
5.9 Adecuar el login al entorno web para el administrador

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#102]
Es necesario adecuar el formulario de login para que también pueda ser usado de manera web por el administrador

**Comment by drvelasquezq** [comment]
Al ejecutar el issue #96 en la que se pretende crear eventos se hizo el inicio de sesión debido a que se considero necesario para continuar con dicha tarea. Por lo anterior esta tarea puede ser cerrada.
![image](https://user-images.githubusercontent.com/23324154/33224340-8d04e9b6-d136-11e7-89cc-298bf16cd4f1.png)
![image](https://user-images.githubusercontent.com/23324154/33224347-9d5eb4ae-d136-11e7-8931-e53dcbf1fd93.png)
