### ISSUE TITLE
5.2 Editar Evento

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#105]
Como usuario administrador puedo realizar modificaciones sobre los eventos, se pueden modificar los siguientes elementos:
+ Editar el Nombre del Eventos
+ Cambiar la Descripción del Eventos
+ Cambiar Fecha y Hora del Evento
+ Cambiar Lugar del Evento (Bogotá y Otras Sedes)
+ Responsable (Nombre, Correo de Contacto)
+ Modificar imagen relacionada
+ Cambiar la Periodicidad del Evento (Semanal, Sólo una vez)
+ Cancelar el Evento

**Comment by hassanmarquez** [comment]
Se realiza la creacion del codigo que permite hacer la edicion de las siguientes caracteristicas de los eventos:
Historia relacionada con la tarea #105

**Comment by EdnaEspejo** [comment]
Se completa código para esta funcionalidad, pendiente integración con el desarrollo realizado.
