### ISSUE TITLE
2.5 Toma de asistencias

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#113]
Identificar en la base de datos la asistencia a un evento, el usuario debe poder confirmar su participación en un evento.

**Comment by SolidS28** [comment]
Los ws se encuentran en ControllerUsersEvents.php
La página html correspondiente es participantes.html (aún falta el botón de acceso si se es el dueño)
El js que maneja esta parte está en confirm.js
