### ISSUE TITLE
T. Construcción JavaScript para el consumo de Servicios

### ISSUE THREAD

**Issue by EdnaEspejo** [polieduco/practicaaplicada20172#119]
Construcción de JavaScript que permita enviar y recibir datos JSON para la validación de usuario

- [x] Construcción del código inicial
- [x] Acordar con el equipo de frontend la información que se entregará
- [x] Acordar con el equipo de backend la información que se recibirá
- [x] Ajustar el código de acuerdo a lo validado con los respectivos grupos
- [x] Pruebas de funcionalidad y publicación

**Comment by EdnaEspejo** [comment]
[app.zip](https://github.com/polieduco/practicaaplicada20172/files/1327929/app.zip)


Construcción del código Inicial:
Para el código inicial se genera una función js para el botón entrar pidiendo que traiga el usuario y contraseña de un JSON ejemplo

![captura](https://user-images.githubusercontent.com/25808635/30788399-86ea6358-a161-11e7-9004-ca67891714b2.JPG)

**Comment by EdnaEspejo** [comment]
Se validó con el grupo de backend la estructura de los JSON a entregar sin embargo continua pendiente una reunión mas formal

**Comment by SolidS28** [comment]
Se hace una reunión con el equipo de desarrollo del backend, se observa que mandamos 3 datos:
-username
-password
-uuid (número único de dispositivo)

Debemos recibir (de acuerdo a la función de directorio activo y base de datos)
-Código de sesión (generado por el directorio)
