### ISSUE TITLE
T. Diseñar un sistema de consultas en la base de datos

### ISSUE THREAD

**Issue by willihamer** [polieduco/practicaaplicada20172#126]
- [ ]  Código de consulta para la tabla USUARIOS
- [ ]  Código de consulta para la tabla TIPOS_USUARIOS
- [ ]  Código de consulta para la tabla EVENTOS
- [ ]  Código de consulta para la tabla SERIES
- [ ]  Código de consulta para la tabla EVENTOS_USUARIOS
- [ ]  Código de consulta para la tabla SEDES
- [ ]  Código de consulta para la tabla CIUDADES
- [ ]  Código de consulta para la tabla SESIONES
- [ ]  Código de consulta para la tabla LOGS
- [ ]  Código de consulta para la tabla FACULTADES

**Comment by willihamer** [comment]
Se crean tareas de consulta

**Comment by degualteros** [comment]
Al igual que #128 esta tarea ya no aplica, ya que según el proceso que se esté haciendo las consultas pueden cambiar y depende de quien lo esté trabajando, de todas formas he creado una carpeta Consultas donde se pueden consultar varios ejemplos de consultas usadas en servicios, de igual forma por el canal BD de Slack se atienden dudas acerca de.
