### ISSUE TITLE
T. Creación de la Conexión

### ISSUE THREAD

**Issue by willihamer** [polieduco/practicaaplicada20172#127]
- [x] Se debe crear el String de conexión desde la aplicación hacia la base de datos
- [x] Crear Script que poble la base de datos

**Comment by degualteros** [comment]
Se cierra tarea ya que en el repositorio se encuentran subidas:
[Poblar Base de datos](https://github.com/polieduco/practicaaplicada20172/blob/master/Db/poblaci%C3%B3nBD.sql)
[Script propuesto para la conexion de la BD](https://github.com/polieduco/practicaaplicada20172/blob/master/Db/class.conexion.php)
