### ISSUE TITLE
T. Crear sistema de inserciones en la base de datos

### ISSUE THREAD

**Issue by willihamer** [polieduco/practicaaplicada20172#128]
- [ ]  Código de inserción para la tabla USUARIOS
- [ ]  Código de inserción para la tabla TIPOS_USUARIOS
- [ ]  Código de inserción para la tabla EVENTOS
- [ ]  Código de inserción para la tabla SERIES
- [ ]  Código de inserción para la tabla EVENTOS_USUARIOS
- [ ]  Código de inserción para la tabla SEDES
- [ ]  Código de inserción para la tabla CIUDADES
- [ ]  Código de inserción para la tabla SESIONES
- [ ]  Código de inserción para la tabla LOGS
- [ ]  Código de inserción para la tabla FACULTADES

**Comment by degualteros** [comment]
Esta tarea ya no aplica, ya que según el proceso que se esté haciendo las consultas pueden cambiar y depende de quien lo esté trabajando, de todas formas  he creado una carpeta [Consultas](https://github.com/polieduco/practicaaplicada20172/tree/master/Db/Consultas) donde se pueden consultar varios ejemplos de consultas usadas en servicios, de igual forma por el canal BD de Slack se atienden dudas acerca de.
