### ISSUE TITLE
T. Ajustes del módulo visualización de eventos

### ISSUE THREAD

**Issue by rzambrano112** [polieduco/practicaaplicada20172#139]
- [ ]  Ajustes del menú del módulo visualización de eventos. 
     Que el diseño sea responsivo con el cambio de tamaño de dispositivos.

- [ ] Ajustes del color menú del módulo visualización de eventos

- [ ] Ajustes en las lista eventos guardados del del módulo visualización de eventos

**Comment by hassanmarquez** [comment]
Historia de usuario fue descartada por modificaciones en el desarrollo del proyecto
