### ISSUE TITLE
2.1.3 Marcar eventos como favoritos.

### ISSUE THREAD

**Issue by mauromara** [polieduco/practicaaplicada20172#14]
Como usuario, debo poder determinar los eventos de mayor interés.

- [ ]  Crear el botón, con el que se pueda determnar los eventos favoritos.
- [ ]  Implementar función que envíe el evento marcado al Modulo II de favoritos de usuario..

**Comment by EdnaEspejo** [comment]
Se considera como un tipo de filtro con la #34
