### ISSUE TITLE
T. Creación de Servicio REST  marcar como favorito

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#143]
- [x] Crear servicio

- [x] integrarlo 

- [x] pruebas 

- [x] Documentación

**Comment by wpradere** [comment]
Se crea los servicios REST  Pero este se reasigna ya que la metodología que se adopto es fullstack

**Comment by rzambrano112** [comment]
Al momento de comenzar con la metodología fullstack nos fue asignado el tema de las notificaciones Push en Android. Y de la misma manera, el tema de crear eventos. Por lo tanto, solo se quiere precisar que esto ya se encuentra en el Master del proyecto #158.
