### ISSUE TITLE
T.Visualizacion de eventos

### ISSUE THREAD

**Issue by hassanmarquez** [polieduco/practicaaplicada20172#148]
- [x] Realiza El front en HTML para la visualización de eventos

- [ ] Implementación de servicio que alimente los eventos nuevos el HTML desde la BD.

- [ ] Empaquetado y puesta a funcionar en apache cordova.

**Comment by Basespoli** [comment]
Se realiza el servicio, con el slim como se indico y se publica en Internet.

![image](https://user-images.githubusercontent.com/25758763/32152423-fec3206c-bcf1-11e7-9e41-7ea49d348561.png)

Se hace el consumo del servicio, y se hace publicación de los eventos en html se están maqueando como eventbrite según las indicaciones, y se realizo la integración del home del menú con algunos de los filtros . 


![image](https://user-images.githubusercontent.com/25758763/32152475-4322093a-bcf2-11e7-94b7-52985500673f.png)

**Comment by Basespoli** [comment]
Se realiza Realiza El front en HTML para la visualización de eventos + consumo de eventos desde base de datos.

![image](https://user-images.githubusercontent.com/25758763/32684006-9a92f49a-c64d-11e7-96bf-2c54152d4104.png)
