### ISSUE TITLE
T.Verificacion de informacion HTML y JS para usabilidad de la interfaz

### ISSUE THREAD

**Issue by hassanmarquez** [polieduco/practicaaplicada20172#149]
- [x] Se debe generar el front de la aplicación para la visualización y usabilidad de los eventos.

**Comment by Basespoli** [comment]
Se genera el maquetación y diseño para los eventos en la parte del front desde el consumo del servicio y con los css y librerias de onsen ui.

![image](https://user-images.githubusercontent.com/25758763/32152713-931514ae-bcf3-11e7-8079-d7de30b9a189.png)

**Comment by hassanmarquez** [comment]
Historia de usuario fue descartada por modificaciones en el desarrollo del proyecto
