### ISSUE TITLE
T. Notificaciones. Investigación de notificaciones y recordatorios de eventos en Apache Cordoba

### ISSUE THREAD

**Issue by rzambrano112** [polieduco/practicaaplicada20172#157]
- [x] Investigación de notificaciones  y recordatorios de eventos en Apache Cordoba.

- [x]  Pruebas Android 

- [x]  Pruebas Ios

**Comment by EdnaEspejo** [comment]
#158

**Comment by wpradere** [comment]
Se realiza la investigación de notificaciones de eventos PUSH en Android estoy haciendo pruebas funcionales.

**Comment by rzambrano112** [comment]
Se realiza igualmente investigación de notificaciones  y recordatorios de eventos en Android y Apache córdoba.

Se realiza una documentación sobre el tema anterior y se comienza a realizar las pruebas pertinentes sobre una aplicación de muestra.
#157

**Comment by rzambrano112** [comment]
Se anexan archivos de pruebas.
[PRUEBASANDROID.pdf](https://github.com/polieduco/practicaaplicada20172/files/1503592/PRUEBASANDROID.pdf)
[PRUEBAS_IOS.pdf](https://github.com/polieduco/practicaaplicada20172/files/1503593/PRUEBAS_IOS.pdf)
Se da cierre al issue #157

**Comment by rzambrano112** [comment]
En relación a esta tarea de notificaciones y recordatorios de eventos en Apache Cordova teniendo en cuenta las plataformas de Android y iOS, se realizan las respectivas pruebas tanto en código como en documentación. En términos generales, se cierra el issue sin ningún aspecto pendiente en este #157.
