### ISSUE TITLE
2.4 Notificaciones y Recordatorios de los Eventos

### ISSUE THREAD

**Issue by EdnaEspejo** [polieduco/practicaaplicada20172#158]
El usuario debe recibir notificaciones acerca de los eventos y el recordatorio de los eventos que tiene asignados para su asistencia.

**Comment by wpradere** [comment]
Se sube el proyecto con las Notificaciones de evento agregado

**Comment by rzambrano112** [comment]
En relación al  issue de notificaciones y recordatorios de los eventos se da cierre teniendo en cuenta  que se realizan  las notificaciones de evento agregado  y ya se encuentra en la Master
#2.4
