### ISSUE TITLE
1.3 Log Out

### ISSUE THREAD

**Issue by EdnaEspejo** [polieduco/practicaaplicada20172#159]
El usuario debe poder finalizar la sesión en la aplicación.

**Comment by hassanmarquez** [comment]
Se realiza el cierre del logout el cual funciona correctamente con la funcionalidad mediante servicios REST.

**Comment by mauromara** [comment]
Se logra hacer el cierre de sesión, junto con su botón.

**Comment by hassanmarquez** [comment]
Se realiza la implementacion del logout tomando como base el código desarollado por @drvelasquezq,
