### ISSUE TITLE
5. Creación BD

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#16]
Propósito es el abarcar todo el proceso de la creación de la base de datos que cumpla con todos los estándares y requerimientos de la aplicación.

Historias de Usuario:

- [ ] 5.1 Analísis de la Base de Datos Módelo Relacional
- [ ] 5.2 Modelado de la base de datos a nivel Lógico.
- [ ] 5.3 Implementación de la base de datos.

**Comment by degualteros** [comment]
Esta tarea está repetida, la que se va a manejar es la #81
