### ISSUE TITLE
T.Acciones Sobre Los Eventos

### ISSUE THREAD

**Issue by CamiloSanch** [polieduco/practicaaplicada20172#162]
se debe:
- [x]  Marcar eventos como favoritos
- [ ]  Marcar eventos a los que asistirá
- [ ]  Cancelar eventos a los que no puede asistir

**Comment by CamiloSanch** [comment]
se creo tan solo los html de cada botón con sus hojas de estilos, la tarea se fue descartando a medida que pasaban los sprints por el retraso general del proyecto, falto crear la lógica funcional y afectar la tabla correspondiente en la base de datos , nos dividimos esa tarea por la complejidad con @AndresMorenoR el se encargo de la cancelación del evento #40 y yo de marcar evento como favorito 
#145, falto encargarnos en relizar la parte de marcar asistencia a los eventos

**Comment by AndresMorenoR** [comment]
Se realizo la funcionalidad de cancelar eventos a los que no puede asistir, se trabajo conjuntamente con @CamiloSanch para el HTML, JS, y el PHP, tarea asociada con #40
