### ISSUE TITLE
T. establecer imagen para un perfil de usuario

### ISSUE THREAD

**Issue by CamiloSanch** [polieduco/practicaaplicada20172#166]
- [ ] se debe permitir cargar una imagen de perfil al usuario en cualquier momento

- [ ] se debe permitir cargar una imagen con unas dimensiones apropiadas 

- [ ]  se debe almacenar la imagen en la base de datos correspondiente

**Comment by CamiloSanch** [comment]
Historia de usuario #33

**Comment by EdnaEspejo** [comment]
Tarea realizada
