### ISSUE TITLE
T. Mostrar Informacion personal de usuario de acuerdo al directorio activo

### ISSUE THREAD

**Issue by hassanmarquez** [polieduco/practicaaplicada20172#168]
Realizar la funciones que permita obtener la información de usuario del directorio activo y mostrarla en el panel de visualizacion.

**Comment by mauromara** [comment]
- Se finaliza la tarea exitosamente, se toman los datos del directorio activo y se muestra en el menú que ya había sido creado, se insertan los datos del usuario en la BD y se editan los archivos correspondientes del proyecto, para dar el resultado que se esperaba.

**Comment by hassanmarquez** [comment]
Se realiza la implementacion del codigo e integracion con la funcionalidad de mostrar Informacion personal de usuario de acuerdo al directorio activo y consultando la existencia del usuario en la base de datos. Tarea correspondiente a la historia de usuario #210. Se realizan pruebas y funciona correctamente.
