### ISSUE TITLE
5.1 Análisis de la Base de Datos Modelo Relacional 

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#17]
Como administrador de base de datos se debe definir un esquema para almacenar la información de la aplicación. Inicialmente se implementaría todo lo necesario para que se pueda realizar el proceso de logueo en la aplicación.

- [x] 5.1.1 Entidades (Tablas) 
- [x] 5.1.2 Definir Relaciones.
- [x] 5.1.3 Definir Llaves (Primarias y Foraneas)
- [ ] 5.1.4 Diagrama E/R  incial de la BD.

**Comment by degualteros** [comment]
Esta no es una historia de usuario y además se repite y/o recoge en la tarea #81 por lo que se cambia etiqueta y se cierra
