### ISSUE TITLE
5.2 Modelado de la Base de Dato a nivel logico

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#18]
Tareas son : 

- [ ]  Crear Base de datos a partir del modelo anterior en el servidor de Mysql 

- [ ] Realizar los INSERT para pruebas mínimos 20 datos por tabla 

- [ ] Crear Scrip y funcionalidad.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #18
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #18  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
