### ISSUE TITLE
T. Integracion de informacion de usuario e imagen de usuario

### ISSUE THREAD

**Issue by hassanmarquez** [polieduco/practicaaplicada20172#190]
Se debe hacer la integracion de la visualizacion de la informacion de usuario con la imagen de usuario, posteriormente la integracion del codigo.

**Comment by hassanmarquez** [comment]
Se realiza la integración de la visualizacion y funcionalidad de la informacion de usuario donde se muestra el ID y el nombre, adicionalmente la imagen la cual se puede seleccionar y cargar.

**Comment by mauromara** [comment]
Se integra el código realizado en donde se lograba subir una imagen de perfil, junto con el menú en donde se evidencia el nombre, apellido y ID del usuario que haya iniciado sesión.

**Comment by hassanmarquez** [comment]
La tarea de usuario esta asociada a la historia #32 correspondiente a la información de usuario.
