### ISSUE TITLE
1.1 Diseño Portal Autenticación

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#2]
usuario deseo ingresar a la aplicación usando usuario y contraseña.

- [x] Creación del Mockup del portal de autenticación.
- [x] Implementación del portal de autenticación mediante JAVA (U otro).
- [ ] Éxito de autenticación
- [ ] Error de autenticación
- [ ] Empaquetado y publicación por Apache Cordova

**Comment by DanteVDrako** [comment]
Se diseñó e implemento mediante HTML5, CCS y JavaScript el portal de autenticación para el proyecto, esta tarea está relacionada al commit fc4ae2b.

**Comment by jolarter** [comment]
Para la parte de PHP se abre la tarea #50.

**Comment by rzambrano112** [comment]
![image](https://user-images.githubusercontent.com/20976993/30998738-52b22426-a496-11e7-935c-cc80e518298a.png)

Diseño Portal Autenticación #2

**Comment by rzambrano112** [comment]
Marvel Prototype for Práctica Aplicada
https://marvelapp.com/2fjahgg/screen/31986741
By Nicolas Vivas
Nuevos prototipos

**Comment by rzambrano112** [comment]
Marvel Prototype for Práctica Aplicada #2 By Nicolas Vivas
![image](https://user-images.githubusercontent.com/20976993/31040837-d4ccc676-a551-11e7-8002-b71397f83cf5.png)
![image](https://user-images.githubusercontent.com/20976993/31040842-d9941cd6-a551-11e7-95dc-06858c71a076.png)

![image](https://user-images.githubusercontent.com/20976993/31040850-de59de22-a551-11e7-873f-95be993ba0e4.png)
![image](https://user-images.githubusercontent.com/20976993/31040855-e7636826-a551-11e7-8e19-13e7bf056337.png)
![image](https://user-images.githubusercontent.com/20976993/31040857-ec01e538-a551-11e7-8cbd-0e40648ec1c4.png)

![image](https://user-images.githubusercontent.com/20976993/31040861-f0bf9f98-a551-11e7-8348-e54572291151.png)

![image](https://user-images.githubusercontent.com/20976993/31040863-f6402550-a551-11e7-9283-e81e8a3c53dc.png)

![image](https://user-images.githubusercontent.com/20976993/31040867-fad5432a-a551-11e7-8a1b-9b4f1bc861b2.png)

![image](https://user-images.githubusercontent.com/20976993/31040869-fffcfe06-a551-11e7-9b0d-0ea07684bdb9.png)

![image](https://user-images.githubusercontent.com/20976993/31040870-0546a39e-a552-11e7-9ff9-3c84debe5725.png)

**Comment by EdnaEspejo** [comment]
Continúan actividades pendientes, se traslada al sprint 3

**Comment by juanSebastianRodriguez** [comment]
Las tareas que surjan para esta historia de usuario deben estar ligadas con el numero del issue en algún comentario de dicha tarea.

**Comment by willihamer** [comment]
Buen día,

Compañeros quisiera confirmar cual debe ser el largo mínimo que se determino para las contraseñas en esta historia de usuario. Ya se tiene que debe tener mínimo una mayúscula un carácter especial y un número.

**Comment by AndresMorenoR** [comment]
Buenas noches.
Compañeros sobre esta tarea, que hace falta para el empaquetado? @SolidS28 @DanteVDrako Gracias.

**Comment by AndresMorenoR** [comment]
Buenas noches.
Compañeros sobre esta tarea, que hace falta para el empaquetado? @SolidS28 @DanteVDrako Gracias.
