### ISSUE TITLE
4.1 Creación formulario Principal

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#20]
Tareas : 

- [ ] Esquema del formulario HTML , Javascrip 

- [ ] Creación de filtros 

- [ ] Agregar calendario y validación de selección de fecha 

- [ ] Integración proyecto Deploy y pruebas a la BD con el CRUD Servicios Web 

- [ ] Validación de identidad de usuario Token

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #20
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #20  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
