### ISSUE TITLE
4.2 Creación portal de consulta asesorías 

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#21]
Tarea de proyecto : 
 

- [ ] Diseño consulta Html y Javascrip 

- [ ] Verificación consumo servicios  y verificación de datos  

- [ ] Validación identidad usuario por tokent

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #21
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #21  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
