### ISSUE TITLE
T. Edición de los eventos creados

### ISSUE THREAD

**Issue by hassanmarquez** [polieduco/practicaaplicada20172#218]
Se realizara la creación de las tareas a realizar para la historia #105.

- [x] Editar el Nombre del Eventos
- [x] Cambiar la Descripción del Eventos
- [x] Cambiar Fecha y Hora del Evento
- [x] Cambiar Lugar del Evento (Bogotá y Otras Sedes)
- [x] Responsable (Nombre, Correo de Contacto)
- [x] Modificar imagen relacionada
- [x] Cambiar la Periodicidad del Evento (Semanal, Sólo una vez)
- [x] Cancelar el Evento

**Comment by CamiloSanch** [comment]
se realiza la integración de  visualizar y permitir cambiar la foto de perfil del usuario, guardando la imagen localmente y la ruta de la imagen en la base de datos

**Comment by CamiloSanch** [comment]
![Uploading Captura.JPG…]()

**Comment by hassanmarquez** [comment]
Se realiza la creacion del codigo que permite hacer la edicion de las siguientes caracteristicas de los eventos:

Tarea relacionada con la historia #105 
  
Editar el Nombre del Eventos
 Cambiar la Descripción del Eventos
 Cambiar Fecha y Hora del Evento
 Cambiar Lugar del Evento (Bogotá y Otras Sedes)
 Responsable (Nombre, Correo de Contacto)
 Modificar imagen relacionada
 Cambiar la Periodicidad del Evento (Semanal, Sólo una vez)
 Cancelar el Evento

Se realiza un formulario basico donde se encuentra los eventos a editar. Se realizan pruebas y funciona correctamente.

**Comment by mauromara** [comment]
Se integra un formulario al menú del home en la aplicación, en donde se evidencian los eventos guardados en la BD, se habilitan para su edición y posterior actualización. Se tiene en cuenta que esta edición debe ser en el modo administrador.
