### ISSUE TITLE
6.1 Implementación del servidor

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#25]
Como administrador deseo tener un ambiente de storage y desplegue de la aplicación para poder mantener visible la aplicación a la institución.

Tarea de proyecto: 

- [ ] 6.1.1 Instalación de S.O
- [ ] 6.1.2 Implementación servicio web

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #25
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #25  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #25
