### ISSUE TITLE
6.1.1 Instalación de S.O

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#26]
Como administrador debo preparar el ambiente de servidor para alojar la aplicación.

Tarea de proyecto:

- [ ] Definición de S.O
- [ ] Instalación del S.O
- [ ] Instalación de actualizaciones o paquetes de seguridad.
- [ ] Instalación de drivers o controladores para compatilidad del Hardware.
- [ ] Conexión a la red de Poligran.
- [ ] Matricula al dominio de Poligran, con nombre de máquina.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #26
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #26  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #26
