### ISSUE TITLE
6.1.2 Implementación servicio Web

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#27]
Como administrador debo preparar el servicio que realice la publicación de la aplicación en la web.

Tarea de proyecto :

- [ ] Instalación del servicio web Apache 
- [ ] Instalación del servicio de depliegue Glassfish.
- [ ] Subir los servicios.
- [ ] Configurar los puertos de conexión de la aplicación. Por defecto Port:80.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #27
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #27  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #27
