### ISSUE TITLE
6.2 Implementación Base de datos

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#28]
Como administrador debo implementar una base de datos que permita almacenar la información generada de la app.

Tarea de proyecto:

- [ ] 6.2.1 Implementación del servicio SQL.
- [ ] 6.2.2 mplementación script base de datos.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #28
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #28  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #28
