### ISSUE TITLE
6.2.1 Implementación del Servicio SQL

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#29]
Como administrador quero implementar el servcio SQL para el montaje de la base de datos.
Tarea de proyecto:
- [ ] Instalación del gestor de base de datos SQL.
- [ ] Subir el servicio y preparar lo para el montaje del mismo.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #29
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #29  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #29
