### ISSUE TITLE
1.1.2 Exito de Autenticación

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#3]
Como usuario y usando autenticación correcta quiero acceder a la aplicación.

- [x] Mockup de autenticación exitosa.
- [x] Implementación de autenticación exitosa. 
- [ ] Conexión con servicio de autenticación.

**Comment by SolidS28** [comment]
Falta paramétrizar los servicios dentro del front para poder realizar su consumo, por ahora están con un servicio dummy para realizar pruebas

**Comment by EdnaEspejo** [comment]
La funcionalidad está incluida en la historia 1.1. Diseño Portal Autenticación #2
