### ISSUE TITLE
6.2.2 Implementación Script Base de datos.

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#30]
Como administrador debo preparar un script SQL que posea todas las caracteristicas que estarán en la BD.
Tarea de proyecto:
- [ ] Exportar un script SQL del diseño hecho en el apartado 3.Creación de BD.
- [ ] Importar el script SQL al servicio en el sevidor principal.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #30
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #30  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #30
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #30  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #30
