### ISSUE TITLE
3.2 Información Usuario

### ISSUE THREAD

**Issue by mauromara** [polieduco/practicaaplicada20172#32]
Como desarrollador, debo mostrar información personal del usuario, según el directorio activo de la universidad.

- [x] No permitir modificación de dicha información.
- [x] Hacer conexión con la BD y mostrar la información.

**Comment by hassanmarquez** [comment]
Se realiza el desarrollo de la funcionalidad y visualización de la información de usuario teniendo en cuenta las siguientes caracteristicas.

- No permitir modificación de dicha información.
- Hacer conexión con la BD y mostrar la información

**Comment by mauromara** [comment]
Se cumple con el desarrollo de esta tarea, en donde el usuario puede visualizar su información n la aplicación y adicionalmente no puede editarla, cumpliendo con lo requerido.
