### ISSUE TITLE
2.3 Listar Eventos con Filtros

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#34]
Como usuario deseo filtrar los eventos del portal principal solo por las que a mi me interesan.

- [x] 2.3.1 Filtros por Categoria
- [x] 2.3.2 Filtros por Lugar
- [x] 2.3.3 Filtros por fecha
- [x] 2.3.4 Filtros por Facultad
- [x] 2.3.5 Filtros por Favoritos
- [x]  Creación de los JS para filtros.

**Comment by Basespoli** [comment]
En el momento se están terminando de crear los filtros en html, continuando el trabajo de mis compañeros  @hassanmarquez  y @andres100r  en el modulo de eventos.

![image](https://user-images.githubusercontent.com/25758763/30769218-b280cb70-9fda-11e7-8f84-4fe2503dee04.png)

**Comment by Basespoli** [comment]
Se generan los filtros con el framework onsen ui, y se exporta a codepen.
`<ons-list>
    <ons-list-header>CATERGORIAS</ons-list-header>
    <ons-list-item tappable>
      <label class="left">
        <ons-checkbox input-id="check-1"></ons-checkbox>
      </label>
      <label for="check-1" class="center">
        Laboratorios
      </label>
    </ons-list-item>
    <ons-list-item tappable>
      <label class="left">
        <ons-checkbox input-id="check-2"></ons-checkbox>
      </label>
      <label for="check-2" class="center">
        Bienestar
      </label>
    </ons-list-item>
  </ons-list>
<ons-list-item tappable>
      <label class="left">
        <ons-checkbox input-id="check-2"></ons-checkbox>
      </label>
      <label for="check-2" class="center">
        Asesorias
      </label>
    </ons-list-item>
<ons-list-item tappable>
      <label class="left">
        <ons-checkbox input-id="check-2"></ons-checkbox>
      </label>
      <label for="check-2" class="center">
        Actividades
      </label>
    </ons-list-item>
<ons-list-item tappable>
      <label class="left">
        <ons-checkbox input-id="check-2"></ons-checkbox>
      </label>
      <label for="check-2" class="center">
        Semilleros
      </label>
    </ons-list-item>
<ons-list-item tappable>
      <label class="left">
        <ons-checkbox input-id="check-2"></ons-checkbox>
      </label>
      <label for="check-2" class="center">
        Otros
      </label>
    </ons-list-item>
  <ons-list>
    <ons-list-header>Lugar</ons-list-header>
    <ons-list-item tappable>
      <label class="left">
        <ons-radio name="color" input-id="radio-1" checked></ons-radio>
      </label>
      <label for="radio-1" class="center">
        Bogota sede calle 51
      </label>
    </ons-list-item>
    <ons-list-item tappable>
      <label class="left">
        <ons-radio name="color" input-id="radio-2"></ons-radio>
      </label>
      <label for="radio-2" class="center">
        Bogota sede calle Postgrados
      </label>
    </ons-list-item>
  </ons-list>
<ons-list-item tappable>
      <label class="left">
        <ons-radio name="color" input-id="radio-2"></ons-radio>
      </label>
      <label for="radio-2" class="center">
        Bogota sede calle 61
      </label>
    </ons-list-item>
  </ons-list><ons-list-item tappable>
      <label class="left">
        <ons-radio name="color" input-id="radio-2"></ons-radio>
      </label>
      <label for="radio-2" class="center">
        Medellin sede principal
      </label>
    </ons-list-item>
  </ons-list><ons-list-item tappable>
      <label class="left">
        <ons-radio name="color" input-id="radio-2"></ons-radio>
      </label>
      <label for="radio-2" class="center">
        Sede virtual
      </label>
    </ons-list-item>
  </ons-list><ons-list-item tappable>
      <label class="left">
        <ons-radio name="color" input-id="radio-2"></ons-radio>
      </label>
      <label for="radio-2" class="center">
        Bogota sede calle Ciudad
      </label>
    </ons-list-item>
  </ons-list>
</ons-page>`

**Comment by EdnaEspejo** [comment]
Se gestionará con la historia de usuario #11
