### ISSUE TITLE
2.3.4 Filtros por Facultad

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#38]
Como usuario quiero filtrar los eventos por facultad.

- [ ] Diseñar filtro.
- [ ] Implementar filtro.

**Comment by EdnaEspejo** [comment]
Se gestionará con la historia #11

**Comment by hassanmarquez** [comment]
Historia de usuario fue descartada por modificaciones en el desarrollo del proyecto y se gestionara por medio de la historia #11 correspondiente a la visualizacion de eventos
