### ISSUE TITLE
1.1.3 Error de Autenticación.

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#4]
Como usaurio quiero que al ingresar credenciales incorrectas aparezca un aviso de error.

- [x] Mockup del aviso de error de credenciales.
- [x] Implementación del aviso de error de credenciales.

**Comment by SolidS28** [comment]
Es una variación inherente de la autenticación, se cree que la tarea 1.1.3 debe contemplar este cambio y no como una tarea aparte

**Comment by mauromara** [comment]
Buenos días, esta tarea nos la habíamos asignado, porque se encontraba acá como tarea a realizar, por favor no afectar las asignaciones de trabajo

**Comment by SolidS28** [comment]
No se desea afectar la tarea, sólo que dividir en dos casos éxito y no éxito, no es necesario y el cambio ya se encuentra implementado por parte del éxito

**Comment by EdnaEspejo** [comment]
La funcionalidad está incluida en la historia 1.1. Diseño Portal Autenticación #2

**Comment by hassanmarquez** [comment]
Historia de usuario fue descartada por modificaciones en el desarrollo del proyecto
