### ISSUE TITLE
T. Cancelación de eventos

### ISSUE THREAD

**Issue by mauromara** [polieduco/practicaaplicada20172#40]
- [x] HTML: crear botón de cancelación de evento

- [ ] JS: Posibilidad de decir o confirmar sí se quiere cancelar el evento, validación si existe el evento en la Base de datos.

- [x] PHP: Cancelar el evento realizando conexión a la base de datos guardando la selección.

- [ ] SQL: Opción de cancelar eventos en la tabla eventos usuarios

 usuario debo poder cancelar los eventos con un tiempo estipulado.

**Comment by EdnaEspejo** [comment]
Esta tarea pertenece a la historia #156

**Comment by AndresMorenoR** [comment]
Se realiza código HTML y PHP no se logra afectar la base de datos con la funcionalidad del botón. #40
