### ISSUE TITLE
5.1.2 Definición de Relaciones

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#41]
Como administrador debo diseñar como las Entidades se relacionan entre si.
Tarea de proyecto:
- [ ] Definir Relaciones.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #41
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #41  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
