### ISSUE TITLE
5.1.3 Definir Llaves (Primarias y Foraneas)

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#43]
Como administrador debo definir los campos de las llaves Primarias y Foraneas en las entidades para poder relacionar las mismas.

- [x] Definición de llaves.

**Comment by degualteros** [comment]
Este proceso ya se viene realizando en conjunto con la tarea #81, y con el avance que se lleva se puede decir que es una tarea constante pero ya realizada
