### ISSUE TITLE
5.1.4 Diagrama completo de la BD.

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#44]
Como administrador debo dejar un diagrama (dibujado) completo de toda la base de datos con sus entidades, llaves, propiedades y relaciones para así tener una ayuda visual del funcionamiento de la misma.
Tarea de proyecto:
- [ ] Diagramar base de datos.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #44
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #44  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
