### ISSUE TITLE
5.3 Implementación de Base de Datos

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#45]
Como administrador debo implementar la base de datos diseñada en el servidor de base de datos definido en el apartado 6. Infraestructura para poder subir el servicio y empezar a usarla.
Tarea de proyecto:
- [ ] Crear script SQL de la base de datos.
- [ ] Implementar el Script en el servidor de base de datos.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #45
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #45  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
