### ISSUE TITLE
8. Servicios

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#46]
Definición, implementación, prueba y documentación de servicios REST escritos en PHP que permitiran persisitir las entidades importantes de la base de datos. 

Historias de Usuario:

- [ ] 8.1 Definición de Servicios
- [ ] 8.2 Implementación de Servicios.
- [ ] 8.3 Prueba de Servicios.
- [ ] 8.4 Documentación de Servicios. 
- [ ] 8.5 Script en JS que consuma los Servicios desde el FrontEnd.

**Comment by rzambrano112** [comment]
Descartado #46
