### ISSUE TITLE
8.1 Definicion de Servicios

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#47]
Como programador debo definir cuales entidades de la base de datos deben persistir para ser consumidas por el FrontEnd.
Tarea de proyecto:
- [ ] Definición de las entidades.
- [ ] Definición del formato de salida, sea JSON o XML.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #47
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #47  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #47
