### ISSUE TITLE
8.2 Implementación de servicios

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#48]
Como programador debo crear los servicios REST en PHP de las entidades que deben persistir y fueron definidas en el apartado 8.1 Definición de Servicios.

Tarea de proyecto:

- [ ] 8.2.1 Servicio 1
- [ ] 8.2.2 Servicio 2
- [ ] 8.2.3 Servicio 3
- [ ] 8.2.4 Servicio 4

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #48
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #48  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #48
