### ISSUE TITLE
8.3 Prueba de Servicios

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#49]
Como administrador debo probar los servicios REST implementados para validar el correcto funcionamiento de los mismos.

Tarea de proyecto:

- [ ] 8.3.1 Prueba Servicio 1
- [ ] 8.3.2 Prueba Servicio 2
- [ ] 8.3.3 Prueba Servicio 3
- [ ] 8.3.4 Prueba Servicio 4

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #49
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #49  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #49
