### ISSUE TITLE
1.2 Recordar Credenciales.

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#5]
Como usuario quiero obtener un correo con mis credenciales cuando las haya olvidado.

- [x] Montar Estructura de BD  en phpmyadmin  para hacer pruebas.

- [x] Realizar la conexión a la BD.

- [x]  Acomodar el index del front end realizado por Nicolas vivas para usar los jquery O javaScript.

- [x]  Realiza una función para enviar al coreo la contraseña.

 - [x] Implementación.

**Comment by Basespoli** [comment]
Se da cierre a esta tarea ya que se acordó con el equipo de trabajo que las credenciales no se van a recordar mediante correo si no que se integrar con la pagina de recuperación de credenciales de la universidad https://cpo.poligran.edu.co/olvido.aspx para que sea mediante el DA.

**Comment by EdnaEspejo** [comment]
Esta funcionalidad esta incluida en la historia 1.1. Diseño Portal Autenticación #2
