### ISSUE TITLE
T. Creación del servicio REST en PHP del Login 

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#50]
Como administrador debo crear y documentar el servicio protocolo REST correspondiente al login .

Tarea de proyecto:

- [x]  Crear la conexión a la BD 

- [x] Crear el servicio 

- [x]  Probar su funcionalidad 

- [x] Documentarlo

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #50
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #50  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by wpradere** [comment]
Se crea el servicio se hace commit y se realiza la pruebas correspondientes

**Comment by rzambrano112** [comment]
Descartado #50

**Comment by juanSebastianRodriguez** [comment]
Se abre nuevamente para ser usada como la tarea reintegracion del login con php

**Comment by EdnaEspejo** [comment]
Tarea cumplida, login funcional
