### ISSUE TITLE
8.5 Script en JS que consuma los Servicios desde el FrontEnd.

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#51]
Como programador debo contruir un script en JavaScript que consuma desde el FrontEnd los JSON o XML generados por los servicios REST desde el BackEnd.

Tarea de proyecto:

- [ ] Diseñar el script.
- [ ] Implementar Script.
- [ ] Probar Script.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #51
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #51  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

**Comment by rzambrano112** [comment]
Descartado #51
