### ISSUE TITLE
1.2 Verificación Información

### ISSUE THREAD

**Issue by mauromara** [polieduco/practicaaplicada20172#6]
Como desarrollador, debo conectarme con el directorio activo, para comprobar que la información suministrada sea correcta y se puede habilitar el ingreso a la APP.

**Comment by EdnaEspejo** [comment]
Se solicita compartir codigo fuente

**Comment by mauromara** [comment]
Se cumple con lo requerido, en donde se logra conexión con directorio activo, creado en Apache Directory Studio, se comparte el código en la carpeta LDAP, de la master.
