### ISSUE TITLE
10.1 Seguridad y sesión  de usuario ( Token )

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#69]
Tara de proyecto : 

- [ ]  El servicio que se  consuma de debe arrojar un token que verifica la sesión.

- [ ] Esa sesión se debe mantener en todos los módulos de la aplicación hasta que el usuario desee salir de ella.

- [ ]  El token debe tener un nivel de encriptación y un tiempo de vida.

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #69
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #69 no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
