### ISSUE TITLE
2.1 Visualización Eventos

### ISSUE THREAD

**Issue by mauromara** [polieduco/practicaaplicada20172#7]
Creación del visor de eventos en HTML5.

Como usuario deseo ver en la pagina principal de la aplicación los eventos mas actuales que han sido creados.

**Comment by DanteVDrako** [comment]
Se ha estado trabajando en la maquetación HTML5 de la app en el visor de eventos según diseños de Mockup.
![home](https://user-images.githubusercontent.com/25806785/30791353-73e1ae5e-a177-11e7-8bfa-33a5dd4add77.JPG)
![menu](https://user-images.githubusercontent.com/25806785/30791354-73e55112-a177-11e7-8bd6-788ed7400495.JPG)

**Comment by EdnaEspejo** [comment]
Esta historia se gestionara con #11
