### ISSUE TITLE
10.3 Consumo servicio Usuario java scrip

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#70]
Tareas de proyecto : 

- [ ] Verificación de token

- [ ] Agregar usuario 

- [ ] Actualizar servicios 

- [ ] Guardar log con con los datos del usuario fecha y hora

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #70
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #70  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
