### ISSUE TITLE
10.2 Creación servicio Usuario

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#71]
Tareas de proyecto  : 

- [ ]  Debe garantizar el Actualización, edición, Listar y agregar información del usuario requerida 

- [ ] Debe crear Token con encriptación 

- [ ] Realizar la pruebas correspondientes y garantizar el deploy 

- [ ] Documentar servicio

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #71
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #71  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
