### ISSUE TITLE
10.4 Creación y diseño perfil Usuario 

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#73]
Tareas de proyecto : 

- [ ] Creación y diseño  javascrip perfil  

- [ ] Realizar pruebas de actualización y lectura del perfil del usuario 

- [ ] Cambio de Avatar 

- [ ] Actualización de datos se hagan en linea por medio de Ajax

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #73
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #73  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
