### ISSUE TITLE
11.1 Creación de interfaz semillero 

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#75]
Tarea de proyecto: 

- [ ] Creación de formulario semillero 

- [ ] Verificación de consumo de servicio con información de la Bd

- [ ]  Verificación del  html y javascrip en el servidor web con sus filtros correspondientes

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #75
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #75  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
