### ISSUE TITLE
11.2 Creación  de servicio Web Semillero 

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#76]
Tareas de proyecto : 

- [ ] Crear servicio Web en PHP  Actualizar, Leer y Agregar.

- [ ] Realizar pruebas del servicio y garantizar su deploy 

- [ ] Documentar el servicio 

- [ ] Verificar Sesión con token

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #76
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #76  no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
