### ISSUE TITLE
11.3 Seguridad y sesión Semillero Token

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#77]
Tareas : 

- [ ] Debe tener un tiempo de vida y un token Encriptado

- [ ] Debe verificar sesión por medio de token

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #77
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #77 no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
