### ISSUE TITLE
11.4 Creación de interfaz Profesor Semillero

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#78]
Tarea de proyecto : 

- [ ] Se debe crear una interfaz en javascrip donde el profesor pueda aceptar los requerimientos enviados 

- [ ] Se debe generar un login de acuerdo a su perfil

- [ ] Se debe agregar modificar y leer

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #78
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #78 no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo
