### ISSUE TITLE
1.3 Creación de perfiles 

### ISSUE THREAD

**Issue by wpradere** [polieduco/practicaaplicada20172#79]
Tareas : 

- [ ] Se debe crear perfiles  con usuario y contraseña para los interesados y que van a interactuar con la aplicación de acuerdo a sus áreas de interés 

- [ ] Se debe crear usuario y contraseña con verificación de token por sesión y un tiempo de vida garantizando la atomicidad de la información 

- [ ] Se debe documentar los perfiles

**Comment by rzambrano112** [comment]
Creación de perfiles #79

![image](https://user-images.githubusercontent.com/20976993/31303078-2df5b390-aacd-11e7-94f7-18a1e788112d.png)
