### ISSUE TITLE
Distribución por sprint de las tareas de Usuario.

### ISSUE THREAD

**Issue by Basespoli** [polieduco/practicaaplicada20172#85]
Distribución por sprint de las tareas de Usuario.

- [x] Se realiza las distribución por sprint de las historias de usuario, mediante la priorización en un listado donde se determinó que lo que tiene más influencia en la priorización son los entregables del cliente, y la estructura.

**Comment by Basespoli** [comment]
Se realiza la creación de un proyecto  en github en simultáneo Distribución por Sprint , donde se realiza la distribución de historias de usuario con 11 sprint comenzando en el cero, donde están ubicadas todas las historias de usuario.

![image](https://user-images.githubusercontent.com/25758763/30254782-d42b72ba-9662-11e7-9159-23be9c0399db.png)

![image](https://user-images.githubusercontent.com/25758763/30254786-eb243d4e-9662-11e7-8c74-6f4ed7f9a738.png)

**Comment by rzambrano112** [comment]
se da cierre al issue #85 teniendo en cuenta la nueva versión de las historias de usuario presentes en el issue #117

**Comment by rzambrano112** [comment]
Se realiza revisión del issue #85
Teniendo en cuenta los comentarios del profesor Julian Olarte este issue #85 no es una historia de usuario sino una tarea de proyecto. @jolarter @EdnaEspejo

y se da cierre al issue #85
