### ISSUE TITLE
T. Auditoria Mockups e Historias de Usuario

### ISSUE THREAD

**Issue by EdnaEspejo** [polieduco/practicaaplicada20172#87]
Se requiere validar que los mockups realizados para la aplicación satisfagan las historias de usuario creadas, para realizar los ajustes correspondientes.

- [x] Validación y resultados

**Comment by jolarter** [comment]
Any user history has the mockups associated, please note that.

**Comment by EdnaEspejo** [comment]
Se realizó la validación de los mockups disponibles en el enlace https://marvelapp.com/683a334/screen/31439685 y las historias de usuario sumistradas, obteniendo los siguientes resultados, de las historias identificadas los mockups satisfacen en un 79% los que se encuentra plasmado en el documento.
[Auditoria.pdf](https://github.com/polieduco/practicaaplicada20172/files/1301265/Auditoria.pdf)

**Comment by SolidS28** [comment]
Una observación, los últimos mockups fueron los encontrados en [mockups](https://marvelapp.com/2fjahgg) que a nivel de funciones no varia mucho sino de organización
Aquí se elimina funcionalidad:
La aplicación permite generar logros y puntos
Se agrega:
Deslogearse

Y la función se ve implentada la función:
Debe mostrar el error de autenticacion

**Comment by EdnaEspejo** [comment]
En cualquier auditoria todo aquello que no esté en el documento genera una no conformidad, al igual que todo aquello que esté en el documento y no en los mockups.
