### ISSUE TITLE
T. Investigación y Elección de Framework para el Front-end

### ISSUE THREAD

**Issue by SolidS28** [polieduco/practicaaplicada20172#88]
Se requiere escoger un framework que reuna capacidades html5/css3/js que se adapte a las necesidades del proyeto.

- [x] Investigación ¿qué hace un framework de front-end para diseño web?
- [x] Investigación ¿qué frameworks existen y qué pros y contras tienen?
- [x] Selección de un grupo de frameworks a probar
- [x] Selección del framework a usar

**Comment by SolidS28** [comment]
Se hace una investigación de diferentes frameworks y aspectos a tener en cuenta en la elección.
Se hace una selección de 4 frameworks para profundizar y probar:

- Bootstrap
- Ionic
- HTML Kickstart
- Onsen UI

De acuerdo a la información recolectada más la experiencia obtenida con el aprendizaje y el resultado de del mismo se decide usar Onsen UI.

**Comment by jolarter** [comment]
Really agree with the choice. Please let us know what would by the best tutorials. 
This choice change the repository structure???

Thanks.

**Comment by jolarter** [comment]
For example... https://m.youtube.com/watch?v=YYyWCegP4ec

**Comment by SolidS28** [comment]
I started with the official website ["Getting Started"](https://onsen.io/v2/guide/), then I used the simulator tool in https://tutorial.onsen.io/. And finally I practiced with help of StackOverflow and some github projects I found. I will add soon other resources that I used plus some recommendation and examples.

**Comment by juanSebastianRodriguez** [comment]
Se realizo la investigación de 4 diferentes frameworks, después de comparar los 4 se escogió Onse iu como framework principal para el proyecto.

Se cierra issue por tareas cumplidas.
