### ISSUE TITLE
T. Publicacion de Servicios Con PHP

### ISSUE THREAD

**Issue by CamiloSanch** [polieduco/practicaaplicada20172#89]
Se requiere familiarizarse con la estructura del lenguaje PHP, codigo ejecutado del lado del servidor Backend inicialmente se requiere:

- [x]  Saber la estructura del código
- [x]  Publicación de Servicios con PHP
- [x]  Autenticación de Usuarios y Mantener Sesión 
- [x]   Autenticación de Usuarios por Medio de Directorio Activo

**Comment by CamiloSanch** [comment]
esta tarea se ditribuyo posteriormente 
de la cual solo trabajamos la de autenticación de usuarios por medio del directorio activo, relacionada  #118 , inicialmente se trabajo con @mauromara y el la concluyo con @hassanmarquez en los sprint siguientes

**Comment by AndresMorenoR** [comment]
Se trabajo con @CamiloSanch en el #89 este fue realizado por @CamiloSanch y @mauromara
