### ISSUE TITLE
1.1.1 Verificación de Información

### ISSUE THREAD

**Issue by mauromara** [polieduco/practicaaplicada20172#9]
Como desarrollador, debo conectarme con el directorio activo, para comprobar que la información suministrada sea correcta y se puede habilitar el ingreso a la APP.

- [ ] Crear conexión a base de datos de usuarios.

**Comment by rzambrano112** [comment]
Teniendo en cuenta la retroalimentación del profesor Julian Olarte esta issue #9 es un tarea de proyecto.
Por lo tanto, se realiza en el label el cambio de historia de usuario a tarea.

**Comment by rzambrano112** [comment]
Verificación de información #9

![image](https://user-images.githubusercontent.com/20976993/31301278-80bd1f46-aabe-11e7-81b7-8aad2faec0c5.png)

![image](https://user-images.githubusercontent.com/20976993/31301312-af105566-aabe-11e7-8630-b51e3a539ff6.png)

![image](https://user-images.githubusercontent.com/20976993/31301297-99aa8d0e-aabe-11e7-989a-537896a65fa5.png)

By Mauricio
