### ISSUE TITLE
T. Creación de Guía Rápida de comandos Git

### ISSUE THREAD

**Issue by degualteros** [polieduco/practicaaplicada20172#92]
Una guía rapida de comandos que permita consultar dudas operativas concernientes a Git:

- [x] Creacion inicial de la guia en la Wiki

**Comment by degualteros** [comment]
Proceso creado correctamente, debe ser actualizado constantemente

**Comment by jolarter** [comment]
And what is the link to the wiki?

**Comment by degualteros** [comment]
Update:  Link to the fast guide for GIT clicking [Here](https://github.com/polieduco/practicaaplicada20172/wiki/Guia-R%C3%A1pida-de-Comandos-Git).
This fast guide will be updated constantly by comming use of Git

**Comment by degualteros** [comment]
Por ahora no hay más cosas que añadir
