### ISSUE TITLE
12.1 Listado de eventos

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#94]
Como usuario quiero visualizar los eventos recientes para estar actualizado.

Historias de usuario:

- [x] 12.1.1 Modulo: Explorar

- [ ] 12.1.2 Evento Nuevo (Crear)

- [x] 12.1.3 Visualización De Evento

- [ ] 12.1.4 Comentarios de eventos (General)

**Comment by DanteVDrako** [comment]
12.1.1 Modulo: Explorar

Se ha avanzado en la construcción del modulo de explorar (el home de la aplicación)

**Comment by DanteVDrako** [comment]
El avance de esto va así, 

![image](https://user-images.githubusercontent.com/25806785/31062822-29d71570-a6f3-11e7-9184-7faea7b42cec.png)

Tengo algunos problemas con el Menu pues no está siendo responsivo y no puedo aplicarle color a su totalidad, es algo en lo que se continuará trabajando:

![image](https://user-images.githubusercontent.com/25806785/31062839-47d66d6e-a6f3-11e7-9346-9cb05f87ed5d.png)

**Comment by hassanmarquez** [comment]
Historia de usuario fue descartada por modificaciones en el desarrollo del proyecto
