### ISSUE TITLE
5.1 Crear Evento

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#96]
Como usuario administrador puedo crear eventos, el formulario debe estar distribuido de la siguiente manera:
+ Nombre del Eventos
+ Descripción del Eventos
+ Fecha y Hora del Evento
+ Lugar del Evento (Bogotá y Otras Sedes)
+ Responsable (Nombre, Correo de Contacto)
+ Agregar imagen relacionada
+ Periodicidad (Semanal, Sólo una vez)
+ Botón de Editar
+ Botón de Cancelar

**Comment by wpradere** [comment]
Se crea formulario y se sube a Github @EdnaEspejo @drvelasquezq

**Comment by drvelasquezq** [comment]
Se creo el formulario igualmente para la aplicación de administración, es la plantilla del HTML solamente , ya que no se encuentra guardando por falta de funcionalidad (no se alcanzo a ejecutar la escritura del código), esto debido al pensar en el alcance y la realización futura de las funcionalidades, pues se considera que el código es entendible y extensible mas aun que el de la aplicación principal.
![image](https://user-images.githubusercontent.com/23324154/33224426-53780a9c-d137-11e7-9030-3e782bcb8682.png)
![image](https://user-images.githubusercontent.com/23324154/33224434-6581a04a-d137-11e7-94b2-df899301da37.png)
![image](https://user-images.githubusercontent.com/23324154/33224444-7aeca66e-d137-11e7-8902-103b88619b2f.png)
![image](https://user-images.githubusercontent.com/23324154/33224464-a73b6886-d137-11e7-874d-50e0211f70d0.png)

**Comment by drvelasquezq** [comment]
Se cierra la tarea por ultima sprint
