### ISSUE TITLE
5.5 Listar Comentarios de los Eventos (Mod. Administrador)

### ISSUE THREAD

**Issue by DanteVDrako** [polieduco/practicaaplicada20172#98]
Como usuario administrador puedo ver los comentarios que se han realizado sobre los eventos.

**Comment by SolidS28** [comment]
La tarea le falta mejoras visuales pero se encuentra funcional 
WS: ControllerComment.php
JS: comment.js
HTML: eventDetail.html

**Comment by SolidS28** [comment]
No se realizó, aunque se puede tomar en parte lo listado en eventos:
La tarea le falta mejoras visuales pero se encuentra funcional 
WS: ControllerComment.php
JS: comment.js
HTML: eventDetail.html
